---
title: "Assignment 2"
author: "Priyanka Jonnala"
date: "2023-09-22"
output:
  pdf_document: default
  html_document: default
---
```{r}
library(lpSolve)
```
#coefficients of the objective function
```{r}
f.obj <- c(420,360,300,420,360,300,420,360,300)
```
#matrix corresponding to coefficients of constraints by rows
# Do not consider the non-negative constraint; it is automatically assumed
```{r}
f.con <- matrix(c(1,1,1,0,0,0,0,0,0,    #Capacity constraints
                  0,0,0,1,1,1,0,0,0,  
                  0,0,0,0,0,0,1,1,1,    
                  20,15,12,0,0,0,0,0,0, #Storage constraints 
                  0,0,0,20,15,12,0,0,0, 
                  0,0,0,0,0,0,20,15,12, 
                  1,0,0,1,0,0,1,0,0,    #Sales forecast constraints
                  0,1,0,0,1,0,0,1,0,    
                  0,0,1,0,0,1,0,0,1,    
                  900,900,900,-750,-750,-750,0,0,0, #Layoff constraints
                  0,0,0,450,450,450,-900,-900,-900,
                  450,450,450,0,0,0,-750,-750,-750), nrow = 12 , byrow= TRUE)
```
#Directional signs
```{r}
f.dir <- c("<=","<=","<=","<=","<=","<=","<=","<=","<=","=","=","=")
```
#right hand side coefficients
```{r}
f.rhs <- c(750,
           900,
           450,
           13000,
           12000,
           5000,
           900,
           1200,
           750,
           0,
           0,
           0)
```
# Final value
```{r}
lp("max", f.obj, f.con, f.dir, f.rhs)
```
# Variables final values
```{r}
lp("max", f.obj, f.con, f.dir, f.rhs)$solution
```



